### ISSUE TITLE
can't download when there is china text

### ISSUE THREAD

**Issue by faruqeclypst** [IITII/telegraph_downloader#3]

**Comment by IITII** [comment]
Can you tell me more details about "can't download"? Such as Error message or logs. Of course, screenshots are much better.
( By the way, I will update the docs these days.

**Comment by faruqeclypst** [comment]
> Can you tell me more details about "can't download"? Such as Error message or logs. Of course, screenshots are much better.
> ( By the way, I will update the docs these days.

ERR_UNESCAPED_CHARACTERS
I'll screenshot later

**Comment by IITII** [comment]
Hi, @faruqeclypst 
I update the docs just now. Please following the example in the docs step by step.
Please show me the full logs and the urls (better) if any error happend when you are downloading files step by step.
Good luck!

**Comment by faruqeclypst** [comment]
C:\Users\Administrator\Desktop\tele\telegraph_downloader>npm start

> telegraph_downloader@2.0.0 start C:\Users\Administrator\Desktop\tele\telegraph_downloader
> node App.js

2021-03-28 21:18:07.723 INFO  Total urls: 2
2021-03-28 21:18:07.723 INFO  Getting image urls from https://telegra.ph/%E6%B5%8B%E8%AF%95-03-28
2021-03-28 21:18:07.724 INFO  Getting image urls from https://telegra.ph/Contoh-telegraph-02-17
2021-03-28 21:18:08.554 ERROR Get ImageArray failed, url: https://telegra.ph/%E6%B5%8B%E8%AF%95-03-28
2021-03-28 21:18:08.554 ERROR EINVAL: invalid argument, mkdir 'C:\Users\Administrator\Desktop\tele\telegraph_downloader\tmp\测试😀(￣▽￣)~*《🤣🤣🤣》'
{"errno":-4071,"syscall":"mkdir","code":"EINVAL","path":"C:\\Users\\Administrator\\Desktop\\tele\\telegraph_downloader\\tmp\\测试😀(￣▽￣)~*《🤣🤣🤣》"}
Error: EINVAL: invalid argument, mkdir 'C:\Users\Administrator\Desktop\tele\telegraph_downloader\tmp\测试😀(￣▽￣)~*《🤣🤣🤣》'
    at Object.mkdirSync (fs.js:987:3)
    at mkdir (C:\Users\Administrator\Desktop\tele\telegraph_downloader\App.js:50:8)
    at C:\Users\Administrator\Desktop\tele\telegraph_downloader\App.js:103:9
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
2021-03-28 21:18:08.555 INFO  Downloading https://telegra.ph/file/49e5afbbb1028fa8eaeda.jpg...
2021-03-28 21:18:08.556 INFO  Downloading https://telegra.ph/file/1911eceb05d2d97190899.jpg...
2021-03-28 21:18:08.556 INFO  Downloading https://telegra.ph/file/c31af7b023c47105b9f53.jpg...
2021-03-28 21:18:09.293 INFO  Downloaded https://telegra.ph/file/1911eceb05d2d97190899.jpg to C:\Users\Administrator\Desktop\tele\telegraph_downloader\tmp\Contoh telegraph\2.jpg
2021-03-28 21:18:09.306 INFO  Downloaded https://telegra.ph/file/49e5afbbb1028fa8eaeda.jpg to C:\Users\Administrator\Desktop\tele\telegraph_downloader\tmp\Contoh telegraph\1.jpg
2021-03-28 21:18:09.563 INFO  Downloaded https://telegra.ph/file/c31af7b023c47105b9f53.jpg to C:\Users\Administrator\Desktop\tele\telegraph_downloader\tmp\Contoh telegraph\3.jpg

**Comment by IITII** [comment]
1. “Get ImageArray failed”, it's usually a network problem. Proxy will be failed when something happend.
2. "Error: EINVAL: invalid argument, mkdir 'C:\Users", The most likely reason is that there is a problem with your NodeJS environment on Windows. Try another computer?

Refer to: 

* [https://stackoverflow.com/questions/61360415/error-einval-invalid-argument-mkdir-c-users-peter-000-c-users-user-appdat](https://stackoverflow.com/questions/61360415/error-einval-invalid-argument-mkdir-c-users-peter-000-c-users-user-appdat)
* [filename_limitations](https://en.wikipedia.org/wiki/Filename#Comparison_of_filename_limitations)
