### ISSUE TITLE
TypeError: matrix.flat is not a function

### ISSUE THREAD

**Issue by SkrudjReal** [IITII/telegraph_downloader#4]
I have done instructions. git clone... npm i.. npm start and i have given this error:

$ uname -a 
Linux god 5.13.0-44-generic #49~20.04.1-Ubuntu SMP Wed May 18 18:44:28 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

```
scrooge@god:~/Desktop/telegraph_downloader$ npm start

> telegraph_downloader@2.0.0 start /home/scrooge/Desktop/telegraph_downloader
> node App.js

2022-06-08 17:15:35.554 INFO  Total urls: 1
2022-06-08 17:15:35.555 INFO  Getting image urls from https://telegra.ph/Osnovy-kompyuternyh-setej-Tema-8-Protokol-agregirovaniya-kanalov-Etherchannel-10-17
2022-06-08 17:15:36.090 ERROR matrix.flat is not a function
{}
TypeError: matrix.flat is not a function
    at Promise.all.then.matrix (/home/scrooge/Desktop/telegraph_downloader/App.js:156:40)
    at process._tickCallback (internal/process/next_tick.js:68:7)
2022-06-08 17:15:36.093 INFO  Total spent 2ms.
2022-06-08 17:15:36.093 INFO  Download complete!

```

**Comment by IITII** [comment]
Please using node version > 12.10.0.

Show me your env, like node version if it still throw exception with using a high version of node.

**Comment by IITII** [comment]
By the way, this project is include in [https://github.com/IITII/tg_setu_bot.git](https://github.com/IITII/tg_setu_bot.git).
